[tool.poetry]
name = "bililistener"
version = "0.1.4"
description = "BiliBili异步直播监听程序"
authors = ["Shadow403 <admin@shadow403.cn>"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.10"
aiohttp = "3.9.5"
aiosignal = "1.3.1"
annotated-types = "0.7.0"
anyio = "4.6.2.post1"
attrs = "24.2.0"
Brotli = "1.1.0"
certifi = "2024.8.30"
click = "8.1.7"
colorama = "0.4.6"
fastapi = "0.115.2"
frozenlist = "1.4.1"
greenlet = "3.1.1"
h11 = "0.14.0"
httpcore = "1.0.6"
httpx = "0.27.2"
idna = "3.10"
loguru = "0.7.2"
multidict = "6.1.0"
pydantic = "2.9.2"
pydantic_core = "2.23.4"
python-dotenv = "1.0.1"
sniffio = "1.3.1"
SQLAlchemy = "2.0.36"
starlette = "0.40.0"
typing_extensions = "4.12.2"
uvicorn = "0.32.0"
win32-setctime = "1.1.0"
yarl = "1.9.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
